[package]
name = "fancy-hangman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
uuid = { version = "1.1.1", features = ["v4", "fast-rng"] }
rand = "0.8.5"
